# Site settings
title: Manifesto
tag_text: Manifesto
description: Manifest for thepru

# Build settings
markdown: kramdown
highlighter: rouge

# Enable when using kramdown
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false

exclude: ["README.md"]

